name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: checkout leaf
        uses: actions/checkout@v3
        with:
          repository: 'EbrahimTahernejad/leaf'
          path: 'leaf'
          submodules: true
          
      - name: install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          
      - name: install toolchain
        run: |
          cargo install cbindgen
      
      - name: build
        run: |
          cd leaf
          export IPHONEOS_DEPLOYMENT_TARGET=`12.0`
          cp ../build.sh scripts/my_ios_build.sh
          chmod +x scripts/my_ios_build.sh
          ./scripts/my_ios_build.sh
          unset IPHONEOS_DEPLOYMENT_TARGET
      
      - name: create xcframework
        run: |
          cd leaf
          mv target/apple/release/LibLeaf.xcframework .
          zip -r LibLeaf.xcframework.zip LibLeaf.xcframework
       
      - name: detect checksum
        run: |
          export TEMP=`shasum -a 256 leaf/LibLeaf.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP
       
      - name: update package file
        run: |
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"Leaf\"," >> Package.swift
          echo "  platforms: [.iOS(.v12)]," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"Leaf\", targets: [\"Leaf\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .target(name: \"Leaf\", dependencies: [\"LibLeaf\"], path: \"Sources/Leaf\", sources: [\"Leaf.swift\"])," >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"LibLeaf\"," >> Package.swift
          echo "      url: \"https://github.com/EbrahimTahernejad/leaf-mobile/releases/download/${{ github.event.inputs.version }}/LibLeaf.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.FILE_CHECKSUM }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Leaf Lib Release ${{ github.event.inputs.version }}
          commit_user_name: Ebrahim
          commit_user_email: ebrahimtahernejad@gmail.com
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: upload release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: leaf/LibLeaf.xcframework.zip
